=== arkottke/docker-gmrecords/scripts/tasks.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Task Processing Document",
    "description": "Processing instruction document for the PGE cloud processing framework",
    "type": "object",
	"properties": {
	  "programName": {
		"description": "A name that describes the server process (e.g. hazard-analysis)",
		"type": "string"
	  },
	  "itemName": {
		"description": "A name describing the item (unit of work) being processed",
		"type": "string"
	  },
	  "supportedModes": {
		"description": "a list of modes supported by the server process (optional)",
		"type": "array",
		"items": { 
			"type": "string" 
		},
		"minItems": 1,
	    "uniqueItems": true
	  },
	  "fetch": {
		"type": "array",
		"items": [
		  {
			"type": "object",
			"properties": {
			  "name": {
				"description": "A name to describe what this fetch does",
				"type": "string"
			  },
			  "includeWhenMode": {
				"description": "When provided, this fetch will be processed only if the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "excludeWhenMode": {
				"description": "When provided, this fetch will not be processed when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "bucket": {
				"description": "the name of the S3 bucket to fetch from",
				"type": "string"
			  },
			  "key": {
				"description": "the key of the file to retrieve. When expand is false, this can be a prefix",
				"type": "string"
			  },
			  "dest": {
				"description": "the local file path that the file is copied to. A directory name is acceptable.",
				"type": "string"
			  },
			  "expand": {
				"description": "unzip the file. It will be expanded in place. Default is false",
				"type": "boolean"
			  },
			  "excludeFilePattern": {
				"description": "removes files from the fetch when they match one of the patterns in the list",
				"type": "array",
				"items": { "type": "string" 
				},
				"minItems": 1,
				"uniqueItems": true
			  },
			  "exitOnError": {
				"description": "stops processing if an error is encountered. The default is true",
				"type": "boolean"
			  },
			  "required": {
				"description": "when set to true, will attempt even with prior errors. The default is false",
				"type": "boolean"
			  }
			},
			"required": [
			  "name",
			  "bucket",
			  "key",
			  "dest"
			]
		  }
		]
	  },
	  "tasks": {
		"type": "array",
		"minItems": 1,
		"items": [
		  {
			"type": "object",
			"properties": {
			  "name": {
				"description": "a name that describes the process being run",
				"type": "string"
			  },
			  "includeWhenMode": {
				"description": "this item will be processed only when the mode is found in this string. It is possible to specify multiple modes as a delimited list.  (optional)",
				"type": "string"
			  },
			  "excludeWhenMode": {
				"description": "this item will not be processed when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "command": {
				"description": "the shell command to be executed. May use [INPUT_FILE_PATH] macro to specify any files found by searching inputFolder for inputFilePattern",
				"type": "string"
			  },
			  "inputFolder": {
				"description": "the folder to search for input files (optional)",
				"type": "string"
			  },
			  "inputFilePattern": {
				"description": "a pattern used to match for input files (optional)",
				"type": "string"
			  },
			  "outputFolder": {
				"description": "the output folder, will be created before command is run (optional)",
				"type": "string"
			  },
			  "logBehavior": {
				"description": "when 'capture' is specified, redirect and analyze log output (optional)",
				"type": "string"
			  },
			  "exitOnError": {
				"description": "stops processing if an error is encountered. The default is true",
				"type": "boolean"
			  },
			  "required": {
				"description": "when set to true, will attempt even with prior errors. The default is false",
				"type": "boolean"
			  }
			},
			"required": [
			  "name",
			  "command"
			]
		  }
		]
	  },
	  "move": {
		"type": "array",
		"items": [
		  {
			"type": "object",
			"properties": {
			  "name": {
				"type": "string"
			  },
			  "includeWhenMode": {
				"description": "this item will be processed only when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "excludeWhenMode": {
				"description": "this item will not be processed when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "inputFolder": {
				"description": "the folder to copy the files from",
				"type": "string"
			  },
			  "includeFilePattern": {
				"description": "includes files if they match one of the patterns in the array (required)",
				"type": "array",
				"items": { "type": "string" },
				"minItems": 1,
				"uniqueItems": true
			  },
			  "excludeFilePattern": {
				"description": "excludes files if they match one of the patterns in the array (optional)",
				"type": "array",
				"items": { "type": "string" },
				"minItems": 1,
				"uniqueItems": true
			  },
			  "outputFolder": {
				"description": "the folder to copy the files to",
				"type": "string"
			  },
			  "exitOnError": {
				"description": "stops processing if an error is encountered. The default is true",
				"type": "boolean"
			  },
			  "required": {
				"description": "when set to true, will attempt even with prior errors. The default is false",
				"type": "boolean"
			  }
			},
			"required": [
			  "name",
			  "inputFolder",
			  "includeFilePattern",
			  "outputFolder"
			]
		  }
		]
	  },
	  "store": {
		"type": "array",
		"items": [
		  {
			"type": "object",
			"properties": {
			  "name": {
				"type": "string"
			  },
			  "includeWhenMode": {
				"description": "this item will be processed only when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "excludeWhenMode": {
				"description": "this item will not be processed when the mode is found in this string. It is possible to specify multiple modes as a delimited list. (optional)",
				"type": "string"
			  },
			  "bucket": {
				"description": "the name of the bucket to copy the files to",
				"type": "string"
			  },
			  "source": {
				"description": "the file or directory to copy from",
				"type": "string"
			  },
			  "dest": {
				"description": "the S3 path of the file to store to. When 'compress' is True, this should be a zip file name",
				"type": "string"
			  },
			  "compress": {
				"description": "zip the source, or not, default is false",
				"type": "boolean"
			  },
			  "compressSubDirectories": {
				"description": "zip the source subdirectories, default is false",
				"type": "boolean"
			  },
			  "removeOnStore": {
				"description": "remove the zip file when it has been copied, default is true",
				"type": "boolean"
			  },
			  "exitOnError": {
				"description": "stops processing if an error is encountered. The default is true",
				"type": "boolean"
			  },
			  "required": {
				"description": "when set to true, will attempt even with prior errors. The default is false",
				"type": "boolean"
			  }
			},
			"required": [
			  "name",
			  "bucket",
			  "source",
			  "dest"
			]
		  }
		]
	  }
	},
	"required": [
	  "programName",
	  "itemName",
	  "tasks"
	]
  }

=== arkottke/docker-gmrecords/cloudburst/extras/tasks-fetch-store.json
{
    "programName" : "run PS",
    "$schema": "tasks.schema.json",
    "itemName" : "none",
    "fetch": [
        {
            "name" : "fetch-1",
            "bucket" : "${BUCKET_NAME}",
            "key" : "test1/",
            "dest" : "./test1/",
            "excludeFilePattern" : ["GMC*", "SSC*", "Tornado*", "deter*", "Fract*" , "Disagg*"],
            "expand" : false
        }
    ],
    "tasks": [
        {
            "name" : "test",
            "command" : "lks -lkl1233aqwakl ./test1/",
            "logBehavior" : "skip"
        }
    ],
    "store" : [
        {
            "name" : "store-output",
            "bucket" : "${BUCKET_NAME}",
            "source" : "./test1/",
            "dest" : "test1_out/",
            "compress" : false,
            "required" : true
        }
    ]
}

=== arkottke/docker-gmrecords/cloudburst/scripts/tasks-proc.json
{
	"programName": "gmrecords",
	"$schema": "tasks.schema.json",
	"itemName": "${WORK_ITEM}",
	"fetch": [
		{
			"name": "fetch configs",
			"bucket": "${BUCKET_NAME}",
			"key": "database/conf",
			"dest": "/working/conf",
			"exitOnError": true
		},
		{
			"name": "fetch project config",
			"bucket": "${BUCKET_NAME}",
			"key": "database/.gmprocess",
			"dest": "/working/.gmprocess",
			"exitOnError": true
		},
		{
			"name": "fetch workspace file",
			"bucket": "${BUCKET_NAME}",
			"key": "database/downloaded/${WORK_ITEM}/workspace.h5",
			"dest": "/working/data/${WORK_ITEM}/workspace.h5",
			"exitOnError": true
		}
	],
	"tasks": [
		{
			"name": "gmrecords process_waveforms",
			"command": "gmrecords --log ${WORK_ITEM}.log -e ${WORK_ITEM} -n2 --label default process_waveforms"
		},
		{
			"name": "gmrecords compute_station_metrics",
			"command": "gmrecords --log ${WORK_ITEM}.log -e ${WORK_ITEM} -n2 --label default compute_station_metrics"
		},
		{
			"name": "gmrecords compute_waveform_metrics",
			"command": "gmrecords --log ${WORK_ITEM}.log -e ${WORK_ITEM} -n2 --label default compute_waveform_metrics"
		},
		{
			"name": "gmrecords mtables",
			"command": "gmrecords --log ${WORK_ITEM}.log -e ${WORK_ITEM} -n2 --label default mtables"
		},
		{
			"name": "compress mtables",
			"command": "cd data && tar -czf \"$EID/mtables-$EID.tar.gz\" *.csv",
			"exitOnError": false
		}
	],
	"store": [
		{
			"name": "store log output",
			"bucket": "${BUCKET_NAME}",
			"source": "/working/${WORK_ITEM}.log",
			"dest": "database/data/${WORK_ITEM}/process.log",
			"compress": false,
			"exitOnError": true
		},
		{
			"name": "store h5 output",
			"bucket": "${BUCKET_NAME}",
			"source": "/working/data/${WORK_ITEM}/workspace.h5",
			"dest": "database/data/${WORK_ITEM}/workspace.h5",
			"compress": false,
			"exitOnError": true
		},
		{
			"name": "store mtables",
			"bucket": "${BUCKET_NAME}",
			"source": "/working/data/${WORK_ITEM}/mtables-${WORK_ITEM}.tar.gz",
			"dest": "database/data/${WORK_ITEM}/mtables-${WORK_ITEM}.tar.gz",
			"compress": false,
			"exitOnError": true
		}
	]
}

=== arkottke/docker-gmrecords/extras/tasks-gmrecords.json
{
    "programName" : "gmrecords",
    "itemName" : "${WORK_ITEM}",
    "tasks": [
        {
            "name" : "gmrecords",
            "command" : "/working/entrypoint.sh ${WORK_ITEM}",
            "logBehavior" : "skip",
            "outputFolder" : "/working/data",
            "exitOnError" : false
        }
    ],
    "store" : [
        {
            "name" : "store h5 output",
            "bucket" : "${BUCKET_NAME}",
            "source" : "/working",
            "dest" : "output_gmrecords/${WORK_ITEM}",
            "compress" : false
        }
    ]
}

=== arkottke/docker-gmrecords/cloudburst/extras/tasks-haz-dams.json
{
    "programName" : "dam_hazard_analysis",
    "$schema": "tasks.schema.json",
    "itemName" : "${WORK_ITEM}",
    "supportedModes" : ["full", "haz-only", "post"],
    "fetch" : [
        {
            "name" : "get-fault-files",
            "bucket" : "${BUCKET_NAME}",
            "key" : "input/faultfiles.7z",
            "dest" : "./faultfiles.7z",
            "expand" : true
        },
        {
            "name" : "get-input-files",
            "bucket" : "${BUCKET_NAME}",
            "key" : "input/${WORK_ITEM}.7z",
            "dest" : "./Sites/${WORK_ITEM}.7z",
            "expand" : true
        },
        {
            "name" : "get-prior-haz-output",
            "includeWhenMode" : "post",
            "bucket" : "${BUCKET_NAME}",
            "key" : "output/${WORK_ITEM}.7z",
            "dest" : "./Output/${WORK_ITEM}.7z",
            "expand" : true,
            "excludeFilePattern" : ["GMC*", "SSC*", "Tornado*", "deter*", "Fract*" , "Disagg*"]
        },
        {
            "name" : "get-prior-haz-out1",
            "includeWhenMode" : "post",
            "bucket" : "${BUCKET_NAME}",
            "key" : "output/${WORK_ITEM}_out1.7z",
            "dest" : "./Output/${WORK_ITEM}_out1.7z",
            "expand" : true
        }
    ],
    "tasks": [
        {
            "name" : "haz",
            "excludeWhenMode" : "post",
            "command" : "echo '0\n0\n[INPUT_FILE_PATH]' | /opt/haz/haz",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "haz.in",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "haz-back-only",
            "excludeWhenMode" : "post",
            "command" : "echo '0\n0\n[INPUT_FILE_PATH]' | /opt/haz/haz",
            "inputFolder" : "./Sites/",
            "inputFilePattern" : "hazbackonly.in",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "fractiles",
            "excludeWhenMode" : "haz-only",
            "command" : "echo '[INPUT_FILE_PATH]' | /opt/haz/haz-fractiles",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "fractile.in",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "disagg",
            "excludeWhenMode" : "haz-only",
            "command" : "echo '[INPUT_FILE_PATH]' | /opt/haz/haz-uhs-disagg",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "deagg.in",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "haz-deter",
            "excludeWhenMode" : "haz-only",
            "command" : "echo '0\n3\n[INPUT_FILE_PATH]' | /opt/haz/haz",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "deter.in",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "haz-tornado-gmc",
            "excludeWhenMode" : "haz-only",
            "command" : "echo '0\n[INPUT_FILE_PATH]' | /opt/haz/haz-tornado-gmc",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "gmctornado.txt",
            "outputFolder" : "./Output/${WORK_ITEM}"
        },
        {
            "name" : "haz-tornado-ssc",
            "excludeWhenMode" : "haz-only",
            "command" : "echo '[INPUT_FILE_PATH]' | /opt/haz/haz-tornado-ssc",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "inputFilePattern" : "ssctornado.txt",
            "outputFolder" : "./Output/$Dam{SITE_NAME}/Period${PERIOD_ID}"
        }
    ],
    "move" : [
        {
            "name" : "move-haz-log-files",
            "inputFolder" : "./Sites/${WORK_ITEM}",
            "includeFilePattern" : ["*.log"],
            "outputFolder" : "./Output/${WORK_ITEM}",
            "exitOnError": false
        },
        {
            "name" : "move-out1-files",
            "inputFolder" : "./Output/${WORK_ITEM}",
            "includeFilePattern" : ["*.out1"],
            "outputFolder" : "/tmp/Output/${WORK_ITEM}",
            "exitOnError": false
        }
    ],
    "store" : [
        {
            "name" : "store-main-output",
            "bucket" : "${BUCKET_NAME}",
            "source" : "./Output/${WORK_ITEM}",
            "dest" : "output/${WORK_ITEM}.7z",
            "compress" : true,
            "removeOnStore" : false
        },
        {
            "name" : "store-out1-files",
            "excludeWhenMode" : "post",
            "bucket" : "${BUCKET_NAME}",
            "source" : "/tmp/Output/${WORK_ITEM}",
            "dest" : "output/${WORK_ITEM}_out1.7z",
            "compress" : true,
            "removeOnStore" : true,
            "exitOnError": false
        },
        {
            "name" : "store-logs",
            "bucket" : "${BUCKET_NAME}",
            "source" : "./Logs/",
            "dest" : "logs/${WORK_ITEM}.7z",
            "compress" : true,
            "removeOnStore" : false,
            "exitOnError": false,
            "required": true
        }
    ]
}

=== arkottke/docker-gmrecords/cloudburst/scripts/tasks-dl.json
{
	"programName": "gmrecords",
	"$schema": "tasks.schema.json",
	"itemName": "${WORK_ITEM}",
	"fetch": [
		{
			"name": "fetch configs",
			"bucket": "${BUCKET_NAME}",
			"key": "database/conf",
			"dest": "/working/conf",
			"exitOnError": true
		},
		{
			"name": "fetch project config",
			"bucket": "${BUCKET_NAME}",
			"key": "database/.gmprocess",
			"dest": "/working/.gmprocess",
			"exitOnError": true
		}
	],
	"tasks": [
		{
			"name": "running download.sh",
			"command": "bash download.sh ${WORK_ITEM}"
		}
	],
	"store": [
		{
			"name": "store h5 output",
			"bucket": "${BUCKET_NAME}",
			"source": "/working/data/${WORK_ITEM}/workspace.h5",
			"dest": "database/downloaded/${WORK_ITEM}/workspace.h5",
			"compress": false,
			"exitOnError": true
		},
		{
			"name": "store log output",
			"bucket": "${BUCKET_NAME}",
			"source": "/working/${WORK_ITEM}.log",
			"dest": "database/data/${WORK_ITEM}/download.log",
			"compress": false,
			"exitOnError": true
		}
	]
}
